name: retry-eval

on:
  push:
    branches:
      - jf/add-retry-eval-workflow
    paths:
      - .github/workflows/retry-eval.yaml
  workflow_dispatch:
    inputs:
      run_id:
        description: "Completed Valkyrie run ID to retry evaluation for."
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  retry-eval:
    uses: vals-ai/.github/.github/workflows/retry-eval.yaml@main
    with:
      run_id: ${{ inputs.run_id || 'aa0bbe06-2238-4079-8025-e81917fa0eb2' }}
    secrets:
      VALKYRIE_AWS_ROLE_ARN: ${{ secrets.VALKYRIE_AWS_ROLE_ARN }}
