name: update-lockfile

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    uses: vals-ai/.github/.github/workflows/update-lockfile.yaml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
